# Twitter API
twitter:
  api_key: GZ8k65DLA1hQX0fn8GRvnVg4r
  api_secret: grCDB2Ed0eW5GIFVgDqJP3anpzY0cEOj3kYKUJk7JiyM9Baasx

# Facebook API
facebook:
  api_key: 261228314080063
  api_secret: 1ef780d54dfa7f0e19236149a18e8db4

# Soundcloud API
soundcloud: 
  api_key: 854f20c74e55b29bf7f90dcdb88a4f04

# Songkick API
songkick:
  api_key: z2WrpIAVrBRTbEiR